modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/LoveTropics/LTWeather/issues"
license="All Rights Reserved"

[[mods]]
modId="ltweather"
version="${file.jarVersion}"
displayName="LTWeather"
logoFile="itcrowd.png"
authors="Corosus"
description='''
Bridging weather2 and ltminigames together without huge cross source dependencies
'''
