modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/LoveTropics/LTWeather/issues"

[[mods]]
modId="weather2"
version="${file.jarVersion}"
displayName="Weather2"
logoFile="itcrowd.png"
authors="Corosus"
description='''

'''
